name: 'Fetch Crypto Data with nbb'
description: 'Fetch cryptocurrency and stock data using ClojureScript/nbb'
author: 'franksiebenlist'

inputs:
  alpha-vantage-api-key:
    description: 'Alpha Vantage API key for fallback stock data'
    required: false

outputs:
  data-file:
    description: 'Path to the generated crypto-prices.json file'
    value: 'data/crypto-prices.json'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        cd ${{ github.action_path }}
        npm install
        npm install -g nbb
      shell: bash
    - name: Run nbb action
      run: |
        cd ${{ github.action_path }}
        nbb action.cljs
      shell: bash